#!/usr/bin/env bash

#- brightness v0.1
#- 
#- Author: Arthur Vogel
#- Updated: 2017-04-05
#- 
#- Note:
#- This script adjusts keyboard/monitor brightness.
#- Tested on MacBook Pro 11,x
#-  

## Usage: brightness [OPTION]
## 
##      -t      keyboard|monitor
##      -o      +|-<integer>
##
##      -h      Show help options.
##      -v      Print version info.
## 
## Example: brightness -t keyboard -o +2
## 	    brightness -t monitor -o -2
##  

help=$(grep "^## " "${BASH_SOURCE[0]}" | cut -c 4-)
version=$(grep "^#- "  "${BASH_SOURCE[0]}" | cut -c 4-)
 

# set base dir and handler for backlight class
set_vars() {
  case "$OPTARG" in 
    keyboard)
      basedir="/sys/class/leds"
      handler=$basedir"/smc::kbd_backlight"
      ;;
    monitor)
      basedir="/sys/class/backlight"
      handler=$basedir"/intel_backlight"
      ;;
  esac
}

adjust_brightness() {
  if [[ -d $handler ]]; then
    # get current brightness
    old_brightness=$(cat $handler"/brightness")

    # get max brightness
    max_brightness=$(cat $handler"/max_brightness")

    # get current brightness %
    old_brightness_p=$(( 100 * $old_brightness / $max_brightness ))

    # calculate new brightness % 
    new_brightness_p=$(($old_brightness_p $offset))

    # calculate new brightness value
    new_brightness=$(( $max_brightness * $new_brightness_p / 100 ))

    # set the new brightness value
    echo $new_brightness > $handler"/brightness"
    exit 0
  else
    echo -e "You don't have the device handler \"$handler\".\nPlease adjust the variable in set_vars() to your needs!"
    exit 1
  fi
}

while getopts ":hvt:o:" opt; do
  case "$opt" in 
    h)
      echo "$help"
      ;;
    v)
      echo "$version"
      ;;
    t)
      eval set_vars
      ;;
    o)
      offset="$OPTARG"
      eval adjust_brightness
      ;;
  esac
done


